package com.ctl.test.mappers;

import com.ctl.test.model.PeopleEntity;

public interface PeopleServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    int insert(PeopleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    int insertSelective(PeopleEntity record);
}